routes/web.php
<?php

use App\Http\Controllers\MaterielController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfesseurController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');


    Route::resource('materiels', MaterielController::class);
    Route::resource('professeurs', ProfesseurController::class);

    Route::get('home',[HomeController::class,'home'])->name('home');
    Route::get('apropos', [HomeController::class,'apropos'])->name('apropos');
    Route::get('contact', [HomeController::class,'contact'])->name('contact');
    Route::get('service', [HomeController::class,'service'])->name('service');
    Route::get('logout', [HomeController::class,'logout'])->name('logout');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');





});

require __DIR__.'/auth.php';

app/Models/Materiel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Materiel extends Model
{
    use HasFactory;

    protected $fillable = [
        'id', 'nom', 'description', 'inventaire', 'etat'
    ];
}

app/Http/Controllers/MaterielController.php
<?php

namespace App\Http\Controllers;

use App\Models\Materiel;
use Illuminate\Http\Request;

class MaterielController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $materiels = Materiel::latest()->paginate(5);
        return view('materiels.index',compact('materiels'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     */
        public function create()
    {
        return view('materiels.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
        'nom' => 'required',
        'description' => 'required',
        'inventaire' => 'required',
        'etat' => 'required',
    ]);

    Materiel::create($request->all());

    return redirect()->route('materiels.index')->with('success','Materiel ajouter avec success');
    }

    /**
     * Display the specified resource.
     */
    public function show(Materiel $materiel)
    {
        return view('materiels.show',compact('materiel'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Materiel $materiel)
    {
        return view('materiels.edit',compact('materiel'));

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Materiel $materiel)
    {
        $request->validate([
            'nom' => 'required',
            'description' => 'required',
            'inventaire' => 'required',
            'etat' => 'required',
        ]);

        $materiel->update($request->all());

        return redirect()->route('materiels.index')->with('success','Materiel modifier avec  successer');
    }
    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Materiel $materiel)
    {
        $materiel->delete();

        return redirect()->route('materiels.index')->with('success','Materiel supprimer avec  successer');
    }







}

resources/views/materiels/create.blade.php
@extends('materiels.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Ajouter un materiel</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('materiels.index') }}"> Retour</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Error!</strong> <br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

            <a  href="{{ route('materiels.index') }}"> </a>
            <form action="{{ route('materiels.store') }}" method="POST">
    @csrf

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nom:</strong>
                <input type="text" name="nom" class="form-control" placeholder="Name">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Inventaire:</strong>
                <textarea class="form-control" style="height:150px" name="inventaire" placeholder="Inventaire"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Etat:</strong>
                <textarea class="form-control" style="height:150px" name="etat" placeholder="Etat"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/materiels/edit.blade.php
@extends('materiels.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('materiels.index') }}"> Retour</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Error!</strong> <br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('materiels.update',$materiel->id) }}" method="POST">
        @csrf
        @method('PUT')

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nom:</strong>
                    <input type="text" name="nom" value="{{ $materiel->nom }}" class="form-control" placeholder="Nom">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Description">{{ $materiel->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Inventaire:</strong>
                    <textarea class="form-control" style="height:150px" name="inventaire" placeholder="Inventaire">{{ $materiel->inventaire }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Etat:</strong>
                    <textarea class="form-control" style="height:150px" name="etat" placeholder="Etat">{{ $materiel->etat }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/materiels/footer.blade.php
<footer class="bg-dark text-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>&copy; {{ date('Y') }} Gestion des matériels. Tous droits réservés.</p>
            </div>
            <div class="col-md-6 text-end">
                <ul class="list-inline">
                    <li class="list-inline-item"><a href="{{ route('contact') }}">Nos Contact</a></li>
                    <li class="list-inline-item"><a href="{{ route('service') }}">Nos services</a></li>
                    <li class="list-inline-item"><a href="{{ route('materiels.index') }}">Retour</a></li>

                </ul>
            </div>
        </div>
</div>

</footer>

resources/views/materiels/header.blade.php
<nav class="navbar navbar-expand-lg bg-dark text-light py-3">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ route('home')}}">Gestion des materiels</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link"  href="{{ route('apropos')}}"> A Propos  </a>
              </li>

            <li class="nav-item">
                <a class="nav-link"  href="{{ route('materiels.create')}}"> Ajouter un materiel </a>
              </li>
          <li class="nav-item">
            <a class="nav-link"  href="{{ route('materiels.index')}}"> Liste des materiels </a>
          </li>

        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Rechercher">

          <button class="btn btn-outline-success" type="submit">Rechercher</button>
        </form>
      </div>
    </div>
  </nav>

resources/views/materiels/index.blade.php
@extends('materiels.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">

                <h2><center>Systeme De Gestion Des Materiels De L'Isep</center></h2>
            </div>

        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered  table-striped">
        <tr>
            <th>No</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Inventaire</th>
            <th>Etat</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($materiels as $materiel)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $materiel->nom }}</td>
            <td>{{ $materiel->description }}</td>
            <td>{{ $materiel->inventaire }}</td>
            <td>{{ $materiel->etat }}</td>
            <td>
                <form action="{{ route('materiels.destroy',$materiel->id) }}" method="POST">

                    <a class="btn btn-info btn-sm" href="{{ route('materiels.show',$materiel->id) }}">Detail</a>

                    <a class="btn btn-primary btn-sm" href="{{ route('materiels.edit',$materiel->id) }}">Modifier</a>

                    @csrf
                    @method('DELETE')
                    <input onclick="return confirm('Êtes-vous sûr ?')" class="btn btn-danger btn-sm"
                     type="submit" value="Supprimer">


                </form>
            </td>
        </tr>
        @endforeach
    </table>

    {!! $materiels->links() !!}

@endsection

resources/views/materiels/layout.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


  </head>
  <body>
    <header>
        @include('materiels.header')
    </header>
    <main class="container mt-3">
        @yield('content')

    </main>
    <footer>
        @include('materiels.footer')
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

resources/views/materiels/show.blade.php
@extends('materiels.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Detail des materiels</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('materiels.index') }}"> Retour</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nom:</strong>
                {{ $materiel->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Descriptions:</strong>
                {{ $materiel->description }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Inventaire:</strong>
                {{ $materiel->inventaire }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Etat:</strong>
                {{ $materiel->etat }}
            </div>
        </div>
    </div>
@endsection