routes/web.php
<?php

use App\Http\Controllers\MaterielController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfesseurController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');


    Route::resource('materiels', MaterielController::class);
    Route::resource('professeurs', ProfesseurController::class);

    Route::get('home',[HomeController::class,'home'])->name('home');
    Route::get('apropos', [HomeController::class,'apropos'])->name('apropos');
    Route::get('contact', [HomeController::class,'contact'])->name('contact');
    Route::get('service', [HomeController::class,'service'])->name('service');
    Route::get('logout', [HomeController::class,'logout'])->name('logout');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');





});

require __DIR__.'/auth.php';

app/Models/Professeur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Professeur extends Model
{
    use HasFactory;

    protected $fillable = [
         'nom', 'filiere', 'materiel'
    ];
}

app/Http/Controllers/ProfesseurController.php
<?php

namespace App\Http\Controllers;

use App\Models\Professeur;
use Illuminate\Http\Request;

class ProfesseurController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $professeurs = Professeur::all();

        return view('professeurs.index', compact('professeurs'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('professeurs.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nom' => 'required',
            'filiere' => 'required',
            'materiel' => 'required'
        ]);

        Professeur::create($validated);

        return redirect()->route('professeurs.index')
        ->with('success', 'Demande ajouté avec succès!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Professeur $professeur)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Professeur $professeur)
    {
        return view('professeurs.index', compact('professeurs'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Professeur $professeur)
    {
        $validated = $request->validate([
            'nom' => 'required',
            'filiere' => 'required',
            'materiel' => 'required'
        ]);
        $professeur->update($validated);

        return to_route('professeurs.index')
                ->with('success', 'Demande modifié avec succès!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Professeur $professeur)
    {
        $professeur->delete();

        return back()
        ->with('success', 'Catégorie supprimé avec succès !');
    }
}

resources/views/professeurs/create.blade.php
@extends('materiels.layout')

@section('title', "Demande de materiel")

@section("content")
    <div class="row">
        <h3>Formulaire de demande de materiel</h3>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('professeurs.store') }}" method="post">
            @csrf
            @include('professeurs.form')
            <div class="d-grip gap-2">
                <button type="submit" class="btn btn-primary">
                    Ajout du demande
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/professeurs/edit.blade.php
@extends('materiels.layout')

@section('title', "Modification  du demande")

@section("content")
    <div class="row">
        <h3>Formulaire de demande d'un materiel</h3>
    <form action="{{ route("professeurs.update", $professseur->id) }}"
        method="post">
        @csrf
        @method("PUT")

        @include("professeurs.form")

        <div class="d-grip gap-2">
            <button type="submit" class="btn btn-wraning btn-sm">
                Enregistre les modifications
            </button>


        </div>

    </form>
</div>

    @endsection

resources/views/professeurs/form.blade.php
<div class="form-group mb-3">
    <label for="nom">
        Nom complet  :
    </label>
    <input
    value="@isset($professeur->nom ) {{ $professeur->nom }}@endisset"
    required type="text" name="nom" class="form-control">
</div>
<div class="form-group mb-3">
    <label for="filiere">
        Nom du filiere :
    </label>
    <input
    value="@isset($professeur->filiere) {{ $professeur->filiere }}@endisset"
    required type="text" name="filiere" class="form-control">
</div>
<div class="form-group mb-3">
    <label for="materiel">
        Nom du materiel :
    </label>
    <input
    value="@isset($professeur->materiel) {{ $professeur->materiel }}@endisset"
    required type="text" name="materiel" class="form-control">
</div>

resources/views/professeurs/index.blade.php
@extends('materiels.layout')

@section('title', "la liste des demandes")

@section("content")
    <div class="row">
        <h3>Liste des demandes</h3>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{{ route('professeurs.create') }}" class="btn btn-primary">
                Nouvelle demande
            </a>
        </div>
        @if (Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        @endif
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom du chef de filiere</th>
                    <th>Filiere</th>
                    <th>Materiel</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($professeurs as $professeur)
                    <tr>
                        <td>{{ $professeur->nom }}</td>
                        <td>{{ $professeur->filiere }}</td>
                        <td>{{ $professeur->materiel }}</td>
                        <td style="display: flex">
                            <a class="btn btn-warning btn-sm" style="margin-right: 5px"
                               href="{{ route('professeurs.edit', $professeur->id) }}">
                                Modifier
                            </a>
                            <form action="{{ route('professeurs.destroy', $professeur->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <input onclick="return confirm('Êtes-vous sûr ?')" class="btn btn-danger btn-sm"
                                       type="submit" value="Supprimer">
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection